In [5]:
import torch
X = torch.Tensor(2, 3)

In [7]:
torch.cuda.FloatTensor(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')

In [8]:
x = torch.tensor(data = [2.0, 3.0], requires_grad = True)
y = x ** 2
z = 2 * y + 3
x, y, z

(tensor([2., 3.], requires_grad=True),
 tensor([4., 9.], grad_fn=<PowBackward0>),
 tensor([11., 21.], grad_fn=<AddBackward0>))

In [10]:
target = torch.tensor([3.0, 4.0]); target

tensor([3., 4.])

In [11]:
z - target

tensor([ 8., 17.], grad_fn=<SubBackward0>)

In [12]:
loss = torch.sum(torch.abs(z - target)); loss

tensor(25., grad_fn=<SumBackward0>)

In [13]:
loss.backward()

In [14]:
print(x.grad, y.grad, z.grad)
# y와 z는 노드가 아니기 때문에 return 값이 없음

tensor([ 8., 12.]) None None
